language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

env:
  - TESTER_PHP_BIN=php
  - TESTER_PHP_BIN=php-cgi

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

  exclude:
    - php: hhvm
      env: TESTER_PHP_BIN=php-cgi

    - php: hhvm-nightly
      env: TESTER_PHP_BIN=php-cgi

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN tests/
